[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# not sure why but it didn't help
#optimizer = true
#optimizer_runs = 0
#via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
